[package]
name = "avane_ck_rust_lib"
version = "0.1.0"
edition = "2024"

[dependencies]
aes = { version = "0.7", features = ["hazmat"] }
anyhow = "1.0.98"
base64 = "0.22.1"
block-modes = "0.8"
block-padding = "0.3.3"
log = "0.4.27"
serde = "1.0.219"
serde_json = "1.0.140"
